# Generated by Django 3.2.18 on 2023-02-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230216_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
