# Generated by Django 3.2.18 on 2023-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurableDataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ConfigurableData',
        ),
    ]
