# Generated by Django 3.2.18 on 2023-10-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0002_auto_20231003_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurabledatatable',
            name='image',
            field=models.ImageField(default='', upload_to='product_images/'),
        ),
    ]
