# Generated by Django 3.2.18 on 2023-10-04 10:47

from django.db import migrations, models
import storages.backends.s3
import tester.models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_configurabledatatable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurabledatatable',
            name='intrest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='configurabledatatable',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configurabledatatable',
            name='image',
            field=models.ImageField(default=tester.models.default_product_image, storage=storages.backends.s3.S3Storage(), upload_to=''),
        ),
    ]
