# Generated by Django 3.2.18 on 2023-10-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0004_auto_20231004_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurabledatatable',
            name='data',
        ),
    ]
