# Generated by Django 3.2.18 on 2023-10-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0005_remove_configurabledatatable_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurabledatatable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
