# Generated by Django 3.2.18 on 2023-10-06 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_configurabledatatable_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurabledatatable',
            name='intrest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(7.5), django.core.validators.MaxValueValidator(14.0)]),
        ),
    ]
