# Generated by Django 3.2.18 on 2023-10-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_alter_configurabledatatable_intrest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurabledatatable',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='configurabledatatable',
            name='intrest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
