# Generated by Django 3.2.18 on 2024-12-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=False, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('dump_data', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('dump_data', models.JSONField(blank=True, default=dict, null=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.make')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('dump_data', models.JSONField(blank=True, default=dict, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=50)),
                ('type', models.CharField(default=None, max_length=2)),
                ('hex_code_primary', models.CharField(default=None, max_length=50)),
                ('hex_code_secondary', models.CharField(default=None, max_length=50)),
                ('Variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
